"""Codec tests: round-trips for every packet type + golden vectors.

The golden vectors below are REGENERATED by tools/gen_golden.py and must
match scope-app/src/lib/codec.test.ts exactly (both implement
PROTOCOL.md; a wire change regenerates both).
"""
import struct

import pytest

from meshtech_node import codec


# ---------------------------------------------------------------- PULSE

def test_pulse_roundtrip():
    p = codec.Pulse(seq=7, uptime_min=1234, rx_per_hour=5321,
                    feed_airtime_s_per_h=9, active_total=40, origin=0xB17E,
                    section_counts=[3, 5, 8, 2, 0, 1, 4, 6, 3])
    raw = codec.encode_pulse(p)
    assert len(raw) <= codec.TARGET_PAYLOAD
    out = codec.decode_pulse(raw[3:])
    assert out.seq == 7
    assert out.origin == 0xB17E
    assert out.uptime_min == 1234
    assert out.rx_per_hour == 5321
    assert out.feed_airtime_s_per_h == 9
    assert out.active_total == 40
    assert out.section_counts == [3, 5, 8, 2, 0, 1, 4, 6, 3]


# ---------------------------------------------------------------- SECT_SUM

def test_sect_sum_roundtrip():
    s = codec.SectSum(seq=1, section_id=5, active_nodes=7,
                      packet_count=1520, delay_p50_s=3, delay_p90_s=9,
                      origin=0xB17E, route_stubs=[0x1234, 0xABCD])
    raw = codec.encode_sect_sum(s)
    out = codec.decode_sect_sum(raw[3:])
    assert out.section_id == 5
    assert out.active_nodes == 7
    assert out.packet_count == 1520
    assert out.delay_p50_s == 3
    assert out.delay_p90_s == 9
    assert out.origin == 0xB17E
    assert out.route_stubs == [0x1234, 0xABCD]


# ---------------------------------------------------------------- ROUTE

def test_route_roundtrip():
    r = codec.Route(seq=99, section_id=2, route_id=0xBEEF,
                    packet_count=312, delay_med_s=4, last_heard_min=17,
                    origin=0xB17E, prefixes=[0x11, 0x22, 0x33])
    raw = codec.encode_route(r)
    out = codec.decode_route(raw[3:])
    assert out.section_id == 2
    assert out.route_id == 0xBEEF
    assert out.packet_count == 312
    assert out.delay_med_s == 4
    assert out.last_heard_min == 17
    assert out.origin == 0xB17E
    assert out.prefixes == [0x11, 0x22, 0x33]


# ---------------------------------------------------------------- INTRO

def test_intro_roundtrip_with_positions():
    intro = codec.Intro(
        seq=5, origin=0xB17E, center_lat=37.0, center_lon=-122.0,
        span_m=40000.0,
        entries=[
            codec.IntroEntry(prefix=0x11, name="Hilltop", lat=37.1,
                             lon=-122.1),
            codec.IntroEntry(prefix=0x22, name="Relay2"),
            codec.IntroEntry(prefix=0x33),
        ])
    raw = codec.encode_intro(intro)
    out = codec.decode_intro(raw[3:], center_lat=37.0, center_lon=-122.0,
                             span_m=40000.0)
    assert out.seq == 5
    assert out.origin == 0xB17E
    assert [e.prefix for e in out.entries] == [0x11, 0x22, 0x33]
    assert out.entries[0].name == "Hilltop"
    # position reconstructs within delta resolution (~1.2 m at 40 km span)
    assert abs(out.entries[0].lat - 37.1) < 0.002
    assert abs(out.entries[0].lon - -122.1) < 0.004
    assert out.entries[1].lat is None
    assert out.entries[2].name is None


# ---------------------------------------------------------------- LAYOUT

def test_layout_roundtrip():
    l = codec.Layout(seq=3, grid=3, center_lat=37.4419,
                     center_lon=-122.1430, span_m=40000, origin=0xB17E,
                     name="Test area")
    raw = codec.encode_layout(l)
    out = codec.decode_layout(raw[3:])
    assert out.grid == 3
    assert abs(out.center_lat - 37.4419) < 1e-6
    assert abs(out.center_lon - -122.1430) < 1e-6
    assert out.span_m == 40000
    assert out.origin == 0xB17E
    assert out.name == "Test area"


# ---------------------------------------------------------------- SNAP

def test_snap_roundtrip():
    s = codec.Snap(seq=8, snap_id=2, part=1, parts=3, origin=0xB17E,
                   body=b"\x01\x02\x03")
    raw = codec.encode_snap(s)
    out = codec.decode_snap(raw[3:])
    assert out.snap_id == 2
    assert out.part == 1
    assert out.parts == 3
    assert out.origin == 0xB17E
    assert out.body == b"\x01\x02\x03"


# ---------------------------------------------------------------- REFRESH_REQ

def test_refresh_req_roundtrip():
    r = codec.RefreshReq(seq=11, kind=codec.REFRESH_KIND_ROUTE,
                         target=0xBEEF, nonce=0x1234,
                         origin=0x0042, host=0xB17E)
    raw = codec.encode_refresh_req(r)
    out = codec.decode_any(raw)   # full plaintext incl. data_type framing
    assert out.kind == codec.REFRESH_KIND_ROUTE
    assert out.target == 0xBEEF
    assert out.nonce == 0x1234
    assert out.origin == 0x0042   # client's own id
    assert out.host == 0xB17E     # preferred host, 0 = owner decides


def test_refresh_req_defaults_are_owner_decides():
    r = codec.RefreshReq(seq=1, kind=codec.REFRESH_KIND_SECTION,
                         target=4, nonce=5)
    out = codec.decode_refresh_req(codec.encode_refresh_req(r)[3:])
    assert out.host == codec.REFRESH_HOST_ANY
    assert out.origin == 0


def test_refresh_req_rejects_bad_kind():
    with pytest.raises(codec.CodecError):
        codec.encode_refresh_req(codec.RefreshReq(seq=0, kind=9, target=0,
                                                  nonce=0))


# ---------------------------------------------------------------- v1 compat

def test_intro_node_class_roundtrip():
    """Class rides the flags byte (bits 2-3): repeater + companion +
    unknown all survive a roundtrip, and positions/names are unaffected."""
    intro = codec.Intro(
        seq=5, origin=0xB17E, center_lat=37.0, center_lon=-122.0,
        span_m=40000.0,
        entries=[
            codec.IntroEntry(prefix=0x11, name="Hilltop", lat=37.1,
                             lon=-122.1, node_class=codec.NODE_CLASS_REPEATER),
            codec.IntroEntry(prefix=0x22, name="Phone",
                             node_class=codec.NODE_CLASS_COMPANION),
            codec.IntroEntry(prefix=0x33),   # unknown class, no name
        ])
    raw = codec.encode_intro(intro)
    out = codec.decode_intro(raw[3:], center_lat=37.0, center_lon=-122.0,
                             span_m=40000.0)
    assert out.entries[0].node_class == codec.NODE_CLASS_REPEATER
    assert out.entries[1].node_class == codec.NODE_CLASS_COMPANION
    assert out.entries[2].node_class == codec.NODE_CLASS_UNKNOWN
    assert out.entries[0].name == "Hilltop"
    assert abs(out.entries[0].lat - 37.1) < 0.002


def test_intro_node_class_clamps_out_of_range():
    """An over-wide class value clamps into 2 bits, never corrupts
    the name/position flags."""
    entry = codec.IntroEntry(prefix=1, name="X", lat=1.0, lon=1.0,
                             node_class=0x07)
    assert entry.flags & 0x03 == 0x03          # name + position intact
    assert (entry.flags >> 2) & 0x03 == 0x03   # class clamped to reserved


def test_v1_intro_still_decodes_class_unknown():
    """A v1-era intro (flags without class bits) decodes with class 0."""
    v1 = bytes.fromhex(
        "04531a0102000211030748696c6c746f7024002400220105416c696365")
    out = codec.decode_any(v1)
    assert all(e.node_class == 0 for e in out.entries)


def test_v1_packets_still_decode():
    """A v1 (3-byte header) packet decodes with origin 0 - old captures
    and old firmware companions must not break."""
    v1 = bytes.fromhex(
        "0553130103000344d61200a01ce9ff409c0464656d6f")
    layout = codec.decode_any(v1)
    assert layout.origin == 0
    assert layout.grid == 3
    assert layout.name == "demo"


# ---------------------------------------------------------------- guards

def test_payload_budget_respected():
    """Every encodable packet type stays inside the 120-byte target
    with realistic content."""
    pulse = codec.encode_pulse(codec.Pulse(
        seq=0, uptime_min=0, rx_per_hour=0xFFFF, feed_airtime_s_per_h=99,
        active_total=0xFFFF, origin=0xB17E, section_counts=[9] * 25))
    assert len(pulse) <= codec.TARGET_PAYLOAD
    intro = codec.encode_intro(codec.Intro(
        seq=0, origin=0xB17E,
        entries=[codec.IntroEntry(prefix=i, name="N" * 20,
                                  lat=1.0, lon=1.0)
                 for i in range(4)]))
    assert len(intro) <= codec.TARGET_PAYLOAD
    route = codec.encode_route(codec.Route(
        seq=0, section_id=1, route_id=0, packet_count=0, delay_med_s=0,
        last_heard_min=0, origin=0xB17E, prefixes=list(range(8))))
    assert len(route) <= codec.TARGET_PAYLOAD


def test_peek_and_decode_any():
    raw = codec.encode_layout(codec.Layout(seq=1, grid=3,
                                           center_lat=1.0, center_lon=2.0,
                                           span_m=1000, origin=0xB17E,
                                           name="x"))
    assert codec.peek_data_type(raw) == codec.TYPE_LAYOUT
    obj = codec.decode_any(raw)
    assert isinstance(obj, codec.Layout)


def test_unknown_type_raises():
    with pytest.raises(codec.CodecError):
        codec.decode_any(b"\x99\x53\x03\x01\x00\x00")


def test_truncated_payloads_raise_not_crash():
    good = codec.encode_pulse(codec.Pulse(seq=1, uptime_min=2, rx_per_hour=3,
                                          feed_airtime_s_per_h=4,
                                          active_total=5, origin=0xB17E,
                                          section_counts=[1, 2, 3]))
    for cut in range(0, len(good)):
        with pytest.raises(codec.CodecError):
            codec.decode_pulse(good[3:cut])


# ---------------------------------------------------------------- golden vectors
# Regenerate with: python tools/gen_golden.py (writes
# tests/golden_vectors.json; keep in sync with scope-app codec.test.ts).
# The test READS the json - one source of truth, no hand-copied drift.

import json as _json
from pathlib import Path as _Path

GOLDEN = _json.loads((_Path(__file__).parent / "golden_vectors.json")
                     .read_text(encoding="utf-8"))


@pytest.mark.parametrize("name", sorted(GOLDEN.keys()))
def test_golden_vectors(name):
    """Decode the pinned vectors and re-encode; bytes must match."""
    raw = bytes.fromhex(GOLDEN[name])
    obj = codec.decode_any(raw)
    if name == "pulse":
        assert codec.encode_pulse(obj) == raw
    elif name == "sect_sum":
        assert codec.encode_sect_sum(obj) == raw
    elif name == "route":
        assert codec.encode_route(obj) == raw
    elif name == "layout":
        assert codec.encode_layout(obj) == raw
    elif name == "intro":
        intro = codec.Intro(seq=obj.seq, origin=obj.origin,
                            entries=obj.entries,
                            center_lat=0.0, center_lon=0.0, span_m=40000.0)
        assert codec.encode_intro(intro) == raw
    elif name == "refresh":
        assert codec.encode_refresh_req(obj) == raw
