"""Packet-core tests - golden vectors generated from the REFERENCE
library itself (openhop_core/src/pymc_core, PYTHONPATH-injected in
conftest.py), 2026-09-20. The node proves against the same crypto the
box runs, not against its own implementation."""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from meshtech_node.packets import (  # noqa: E402
    FLOOD_DEDUPE_WINDOW_S, PAYLOAD_TYPE_GRP_DATA, PAYLOAD_TYPE_GRP_TXT,
    AdvertInfo, ChannelKeys, FloodDedupe, decode_group_payload,
    derive_channel_keys, parse_advert, secret_bytes, split_frame,
)

# Golden vectors - generated by running CryptoUtils from the reference
# library (2026-09-20, recorded in the session transcript):
#   plaintext = ts(1234567890 LE) | flags 0x00 | "Brett: hello mesh"
#   channel_hash = sha256(b"#scope")[0] = 0x39
#   aes_key = 2373636f706500000000000000000000
#   hmac_key = aes_key || 16 zero bytes
GOLDEN_PLAINTEXT = (1234567890).to_bytes(4, "little") + bytes([0]) \
    + b"Brett: hello mesh"
GOLDEN_CT = bytes.fromhex(
    "d28e60ccfdf9984883ba5953e9c550aa409864a430c85667419ffa975edbf943")
GOLDEN_MAC = bytes.fromhex("ca92")
GOLDEN_AES = bytes.fromhex("2373636f706500000000000000000000")
GOLDEN_HMAC_KEY = GOLDEN_AES + b"\x00" * 16
SCOPE_HASH = 0x39


def test_channel_keys_match_reference():
    ch, aes, hmac_key = derive_channel_keys("#scope")
    assert ch == SCOPE_HASH
    assert aes == GOLDEN_AES
    assert hmac_key == GOLDEN_HMAC_KEY


def test_decode_group_payload_with_reference_ciphertext():
    payload = bytes([SCOPE_HASH]) + GOLDEN_MAC + GOLDEN_CT
    channels = [ChannelKeys.from_secret("#scope", "#scope")]
    out = decode_group_payload(payload, channels)
    assert out is not None
    channel, plaintext, origin_ts = out
    assert channel.name == "#scope"
    assert plaintext[:len(GOLDEN_PLAINTEXT)] == GOLDEN_PLAINTEXT
    assert origin_ts == 1234567890.0


def test_bad_mac_is_honest_none():
    payload = bytes([SCOPE_HASH]) + b"\x00\x00" + GOLDEN_CT
    channels = [ChannelKeys.from_secret("#scope", "#scope")]
    assert decode_group_payload(payload, channels) is None


def test_foreign_channel_hash_is_honest_none():
    payload = bytes([0xAA]) + GOLDEN_MAC + GOLDEN_CT
    channels = [ChannelKeys.from_secret("#scope", "#scope")]
    assert decode_group_payload(payload, channels) is None


def test_crypto_unavailable_is_honest_none():
    import meshtech_node.packets as P
    saved = P._CRYPTO
    P._CRYPTO = None
    P._CRYPTO_ERR = "simulated outage"
    try:
        payload = bytes([SCOPE_HASH]) + GOLDEN_MAC + GOLDEN_CT
        channels = [ChannelKeys.from_secret("#scope", "#scope")]
        assert P.decode_group_payload(payload, channels) is None
    finally:
        P._CRYPTO = saved
        P._CRYPTO_ERR = None


# ------------------------------------------------------------- frames ----

def _build_frame(payload_type: int, route: int, payload: bytes,
                 transport_codes=None, hops: int = 0, hash_size: int = 1,
                 path: bytes = b"") -> bytes:
    header = (0 << 6) | (payload_type << 2) | route
    out = bytes([header])
    if route in (0, 3):
        tc = transport_codes or (0x1122, 0x3344)
        out += tc[0].to_bytes(2, "little") + tc[1].to_bytes(2, "little")
    path_len_byte = ((hash_size - 1) << 6) | (hops & 0x3F)
    out += bytes([path_len_byte]) + path
    return out + payload


def test_split_frame_transport_flood_with_codes():
    # route 0 = TRANSPORT_FLOOD per reference constants.py:16 - carries codes
    frame = split_frame(_build_frame(PAYLOAD_TYPE_GRP_DATA, 0, b"\x01\x02"))
    assert frame is not None
    assert frame.payload_type == PAYLOAD_TYPE_GRP_DATA
    assert frame.route == 0
    assert frame.transport_codes == (0x1122, 0x3344)
    assert frame.hops == 0


def test_split_frame_direct_no_transport_codes():
    frame = split_frame(_build_frame(0x02, 2, b"\x01"))
    assert frame is not None
    assert frame.transport_codes is None
    assert frame.hops == 0


def test_split_frame_path_hops_preserved():
    path = bytes([0xAA, 0xBB, 0xCC, 0xDD])          # 2 hops x 2-byte hashes
    frame = split_frame(_build_frame(0x05, 0, b"\x01", hops=2,
                                     hash_size=2, path=path))
    assert frame is not None
    assert frame.hops == 2
    assert frame.hash_size == 2
    assert frame.path == path
    assert frame.transport_codes == (0x1122, 0x3344)


def test_split_frame_rejects_truncated_path():
    bad = _build_frame(0x05, 0, b"\x01", hops=3, hash_size=1,
                       path=b"\xAA")                # claims 3, carries 1
    assert split_frame(bad) is None


def test_split_frame_rejects_bad_hash_size():
    # flood-header frame whose path_len byte encodes hash_size 4
    bad = bytes([0x14]) + b"\x00" * 4 + b"\xC0" + b"\x01"
    assert split_frame(bad) is None


# ------------------------------------------------------------- dedupe ----

def test_dedupe_scripted_counts():
    """The BENCH-CHECKLIST dedupe script: N=3 distinct, M=2 dup each,
    K=0 drops - health numbers must match the script exactly."""
    dedupe = FloodDedupe(now=1000.0)
    distinct = [b"\x01", b"\x02", b"\x03"]
    dup_count = 2
    seen_first_time = 0
    seen_duplicate = 0
    for payload in distinct:
        for _ in range(dup_count + 1):
            if dedupe.is_duplicate(PAYLOAD_TYPE_GRP_DATA, payload):
                seen_duplicate += 1
            else:
                seen_first_time += 1
    assert seen_first_time == 3
    assert seen_duplicate == 6
    # window expiry: at t=1046 (46 s later) the same payload is new again
    dedupe2 = FloodDedupe(now=1000.0)
    assert dedupe2.is_duplicate(PAYLOAD_TYPE_GRP_DATA, b"\x09") is False
    assert dedupe2.is_duplicate(PAYLOAD_TYPE_GRP_DATA, b"\x09") is True
    dedupe3 = FloodDedupe(now=1000.0)
    dedupe3.is_duplicate(PAYLOAD_TYPE_GRP_DATA, b"\x09")
    dedupe3._now = lambda: 1000.0 + FLOOD_DEDUPE_WINDOW_S + 1
    assert dedupe3.is_duplicate(PAYLOAD_TYPE_GRP_DATA, b"\x09") is False


def test_own_tx_window_longer():
    dedupe = FloodDedupe(now=1000.0)
    dedupe.mark_own_tx(PAYLOAD_TYPE_GRP_DATA, b"\xAB")
    assert dedupe.is_duplicate(PAYLOAD_TYPE_GRP_DATA, b"\xAB") is True
    dedupe._now = lambda: 1000.0 + 121.0
    assert dedupe.is_duplicate(PAYLOAD_TYPE_GRP_DATA, b"\xAB") is False


# ------------------------------------------------------------ adverts ----

def _advert_payload(prefix=0x42, ts=1234567890, flags=0x90,
                    lat=41.7, lon=-111.8, name=b"LoganPeak"):
    payload = bytes([prefix]) + b"\x11" * 31            # 32B pubkey
    payload += ts.to_bytes(4, "little")
    payload += b"\x22" * 64                             # signature
    payload += bytes([flags])
    if flags & 0x10:
        payload += int(lat * 1e6).to_bytes(4, "little", signed=True)
        payload += int(lon * 1e6).to_bytes(4, "little", signed=True)
    if flags & 0x80:
        payload += name
    return payload


def test_parse_advert_full():
    info = parse_advert(_advert_payload())
    assert info is not None
    assert info.prefix == 0x42
    assert info.origin_ts == 1234567890.0
    assert info.flags == 0x90
    assert abs(info.lat - 41.7) < 0.001
    assert abs(info.lon - (-111.8)) < 0.001
    assert info.name == "LoganPeak"
    assert info.node_class == 0                          # flags & 0x0F = 0


def test_parse_advert_no_location():
    info = parse_advert(_advert_payload(flags=0x80))
    assert info.lat is None and info.lon is None
    assert info.name == "LoganPeak"


def test_parse_advert_short_payload_is_none():
    assert parse_advert(b"\x42" + b"\x00" * 50) is None


def test_parse_advert_truncated_location_is_honest():
    # flags say location, bytes missing -> flags-only result, no crash
    payload = bytes([0x42]) + b"\x11" * 31 + (1234567890).to_bytes(4, "little") \
        + b"\x22" * 64 + bytes([0x90]) + b"\x01\x02"
    info = parse_advert(payload)
    assert info is not None
    assert info.lat is None and info.lon is None
