"""Wire codec for the scope feed protocol v1.

Implements PROTOCOL.md exactly. The TypeScript port
(scope-app/src/lib/codec.ts) must stay byte-compatible and pass the
same golden vectors (tests/test_codec.py, generated by
tools/gen_golden.py).

All multi-byte integers are little-endian (MeshCore convention).
"""
from __future__ import annotations

import struct
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

# v1.1 (0x02): + origin in header, + refresh host target.
# v1.2 (0x03, 2026-09-20): SECTION IDS ARE 1-BASED on the wire
# (1 = NW .. 9 = SE, matching what the app prints). 0 is RESERVED and
# means "whole-area" in a REFRESH_REQ target; a SECT_SUM/ROUTE with
# section_id 0 is malformed and rejected at decode. Header layout is
# unchanged from v1.1 (version + seq + origin).
# v1.3 (0x04, 2026-09-23, MAP-SIZE-DESIGN.md): REFRESH_REQ gains an
# optional span_km field (2 LE, kilometres) so a client can ask for a
# 20/40/60 km window of the host's 60x60 home area. 0 = host decides
# (= the whole home box, today's behavior). Older encoders that omit
# the field decode as span_km=0. Header layout unchanged.
# v1.6 (0x06, 2026-09-24, VECTORED-SYNC-DESIGN.md): PER-PACKET
# versioning - only the shapes whose wire changed declare 0x06:
# REFRESH_REQ gains sync_marker (2 LE; the client's vectored-sync
# marker; the host answers with full records only for nodes CHANGED
# after that marker; marker 0 = "not vectored" = byte-identical to
# the v1.5 REFRESH_REQ), and the NEW TYPE_GONE (0x5312) carries the
# retired prefixes (name-supersede, 30-day prune) so a phone can
# REMOVE dots - an honest deletion, not a stale fade. All UNCHANGED
# shapes keep 0x05, so the old web app's strict decoder never sees a
# version it does not know ("the old web app keeps working
# unchanged" - the design's own law). A 0x06 REFRESH_REQ is still
# rejected loudly by every pre-v1.6 decoder - intended: it carries a
# field they cannot read.
PROTO_VERSION = 0x05          # default for UNCHANGED shapes
PROTO_VERSION_REFRESH = 0x06  # REFRESH_REQ (sync_marker added)
PROTO_VERSION_GONE = 0x06     # GONE (new packet)
PROTO_VERSION_INTRO = 0x06    # INTRO (the ruler: span field 3 LE bytes)

# Type GONE (0x5312): vectored-sync deletion notice. Body: seq(2)+
# origin(2) header then count(1) + count x prefix(1). Up to 8.
TYPE_GONE = 0x5312
MAX_GONE_PER_PACKET = 8

# Allowed client window sizes for a refresh (MAP-SIZE-DESIGN section
# 4): 0 = host decides. The snap-to-nearest choice lives in the
# callers (config/service), not the codec - the wire just carries the
# number.
REFRESH_SPAN_HOST_DECIDES = 0

# REFRESH_REQ target 0 = WHOLE-AREA refresh (any kind): the answer is
# LAYOUT + one summary per section + node names. Section targets are
# 1..grid*grid. Never a square: that is the whole point (Brett
# 2026-09-20 - "section 0" in a log confused humans and it also meant
# the wire could not say "the whole map" and "upper-left" apart).
REFRESH_WHOLE_AREA = 0

# data_type values (the 0x53 magic marks scope traffic)
TYPE_PULSE = 0x5301
TYPE_SECT_SUM = 0x5302
TYPE_ROUTE = 0x5303
TYPE_INTRO = 0x5304
TYPE_LAYOUT = 0x5305
TYPE_SNAP = 0x5306
TYPE_REFRESH_REQ = 0x5311
TYPE_GONE = 0x5312
# HEARTBEAT (0x5313, Brett's airtime rule 2026-09-26): the phone app's
# tiny keep-alive. NO body beyond the 5-byte header - nothing to go
# stale, nothing to misread. Its ARRIVAL is the whole message: a live
# app is on the air listening.
TYPE_HEARTBEAT = 0x5313
# CLINIC (0x5314, Mesh Clinic v2 Phase 1, CLINIC-WIRE.md): the mesh
# clinic's facts + provenance - a stream of small RECORDS (node facts,
# route facts, trouble flags, peer reports). ONE type for the whole
# health layer; every record carries `source` = the box that measured
# or reported it (first-hand vs second-hand rides the bytes).
TYPE_CLINIC = 0x5314

TYPE_NAMES = {
    TYPE_PULSE: "PULSE",
    TYPE_SECT_SUM: "SECT_SUM",
    TYPE_ROUTE: "ROUTE",
    TYPE_INTRO: "INTRO",
    TYPE_LAYOUT: "LAYOUT",
    TYPE_SNAP: "SNAP",
    TYPE_REFRESH_REQ: "REFRESH_REQ",
    TYPE_GONE: "GONE",
    TYPE_HEARTBEAT: "HEARTBEAT",
    TYPE_CLINIC: "CLINIC",
}

# CMD_SEND_CHANNEL_DATA payload budget (openhop_core constants.py:
# MAX_FRAME_SIZE 172 - 9). We target <= 120 bytes of plaintext.
MAX_CHANNEL_DATA = 163
TARGET_PAYLOAD = 120

# LAYOUT/INTRO name length cap
MAX_NAME = 31

REFRESH_KIND_SECTION = 1
REFRESH_KIND_ROUTE = 2
REFRESH_HOST_ANY = 0x0000   # "owner decides" (v1.1 election)

# INTRO flags bits 2-3: node class (v1.1). 0 = unknown (the honest
# default when the host's source data does not classify nodes).
NODE_CLASS_UNKNOWN = 0x00
NODE_CLASS_REPEATER = 0x01
NODE_CLASS_COMPANION = 0x02
NODE_CLASS_RESERVED = 0x03
NODE_CLASS_SHIFT = 2
NODE_CLASS_MASK = 0x03


class CodecError(Exception):
    """Raised when a payload cannot be decoded; message says why."""


# --------------------------------------------------------------------------
# Header helpers
# --------------------------------------------------------------------------

def pack_header(seq: int, origin: int = 0, **kwargs) -> bytes:
    """proto_version(1) + seq(2 LE) + origin(2 LE).

    origin = first 2 bytes of the host's pubkey - identifies the sender
    when several scope hosts share the channel (v1.1). v1 compat: the
    decoder maps version-0x01 3-byte headers to origin 0x0000.
    version (kwarg, v1.6): per-packet protocol version - only the
    shapes whose wire changed declare 0x06 (REFRESH_REQ, GONE); the
    default PROTO_VERSION (0x05) covers every unchanged shape.
    """
    if not 0 <= int(seq) <= 0xFFFF:
        raise CodecError(f"seq out of range: {seq}")
    if not 0 <= int(origin) <= 0xFFFF:
        raise CodecError(f"origin out of range: {origin}")
    version = kwargs.pop("version", PROTO_VERSION)
    if kwargs:
        raise CodecError(f"unknown header kwargs: {sorted(kwargs)}")
    return struct.pack("<BHH", version, int(seq), int(origin))


@dataclass
class Header:
    version: int
    seq: int
    origin: int = 0


def unpack_header(payload: bytes, offset: int = 0) -> Tuple[Header, int]:
    if len(payload) < offset + 3:
        raise CodecError("payload too short for header")
    version = payload[offset]
    if version == 0x01:
        # v1 packet: 3-byte header, no origin field.
        seq = struct.unpack_from("<H", payload, offset + 1)[0]
        return Header(version=version, seq=seq, origin=0), offset + 3
    if version not in (0x02, 0x03, 0x04, 0x05, 0x06):
        # STRICT: an unknown version must not be silently read with the
        # wrong field widths (0x01 = 3-byte, 0x02+ = 5-byte). A loud
        # error beats a confident misread.
        raise CodecError(f"unsupported protocol version 0x{version:02x}")
    if len(payload) < offset + 5:
        raise CodecError("payload too short for v1.1 header")
    seq, origin = struct.unpack_from("<HH", payload, offset + 1)
    return Header(version=version, seq=seq, origin=origin), offset + 5


def data_type_bytes(data_type: int, body: bytes) -> bytes:
    """Full GRP_DATA plaintext: data_type(2 LE) + data_len(1) + body.

    data_len covers the header+body (everything after the data_type
    field), matching the companion framing.
    """
    if not 0 <= data_type <= 0xFFFF:
        raise CodecError(f"data_type out of range: {data_type:#x}")
    if len(body) > 255:
        raise CodecError(f"body too long: {len(body)} > 255")
    return struct.pack("<HB", data_type, len(body)) + body


# --------------------------------------------------------------------------
# PULSE (0x5301)
# --------------------------------------------------------------------------

@dataclass
class Pulse:
    seq: int
    uptime_min: int
    rx_per_hour: int
    feed_airtime_s_per_h: int
    active_total: int
    origin: int = 0
    section_counts: List[int] = field(default_factory=list)


def encode_pulse(p: Pulse) -> bytes:
    if len(p.section_counts) > 255:
        raise CodecError("too many sections")
    body = pack_header(p.seq, p.origin)
    body += struct.pack(
        "<HHHHB",
        _u16(p.uptime_min, "uptime_min"),
        _u16(p.rx_per_hour, "rx_per_hour"),
        _u16(p.feed_airtime_s_per_h, "feed_airtime_s_per_h"),
        _u16(p.active_total, "active_total"),
        len(p.section_counts),
    )
    for count in p.section_counts:
        body += struct.pack("<B", _u8(count, "section count"))
    return data_type_bytes(TYPE_PULSE, body)


def decode_pulse(payload: bytes) -> Pulse:
    header, off = unpack_header(payload)
    if len(payload) < off + 9:
        raise CodecError("PULSE too short")
    uptime, rx, air, total, n = struct.unpack_from("<HHHHB", payload, off)
    off += 9
    if len(payload) - off < n:
        raise CodecError("PULSE section counts truncated")
    counts = [payload[off + i] for i in range(n)]
    return Pulse(seq=header.seq, uptime_min=uptime, rx_per_hour=rx,
                 feed_airtime_s_per_h=air, active_total=total,
                 origin=header.origin, section_counts=counts)


# --------------------------------------------------------------------------
# SECT_SUM (0x5302)
# --------------------------------------------------------------------------

@dataclass
class SectSum:
    seq: int
    section_id: int
    active_nodes: int
    packet_count: int
    delay_p50_s: int
    delay_p90_s: int
    origin: int = 0
    route_stubs: List[int] = field(default_factory=list)  # route_ids


def _check_section_id(value: int, where: str) -> int:
    """Wire section ids are 1-BASED (v1.2): 1..255 valid on the byte.

    0 is reserved (whole-area marker in REFRESH_REQ targets); a
    SECT_SUM/ROUTE carrying 0 is malformed - reject at the boundary
    instead of drawing a phantom NW square."""
    value = _u8(value, where)
    if value == REFRESH_WHOLE_AREA:
        raise CodecError(f"{where}: 0 is reserved (whole-area)")
    return value


def encode_sect_sum(s: SectSum) -> bytes:
    if len(s.route_stubs) > 255:
        raise CodecError("too many route stubs")
    body = pack_header(s.seq, s.origin)
    body += struct.pack(
        "<BBHHHBB",
        _check_section_id(s.section_id, "section_id"),
        _u8(s.active_nodes, "active_nodes"),
        _u16(s.packet_count, "packet_count"),
        _u16(s.delay_p50_s, "delay_p50_s"),
        _u16(s.delay_p90_s, "delay_p90_s"),
        0,  # reserved byte keeps the struct readable
        len(s.route_stubs),
    )
    for rid in s.route_stubs:
        body += struct.pack("<H", _u16(rid, "route_id"))
    return data_type_bytes(TYPE_SECT_SUM, body)


def decode_sect_sum(payload: bytes) -> SectSum:
    header, off = unpack_header(payload)
    if len(payload) < off + 10:
        raise CodecError("SECT_SUM too short")
    section_id, active, packets, p50, p90, _reserved, n = \
        struct.unpack_from("<BBHHHBB", payload, off)
    off += 10
    _check_section_id(section_id, "decoded section_id")
    if len(payload) < off + 2 * n:
        raise CodecError("SECT_SUM stubs truncated")
    stubs = [struct.unpack_from("<H", payload, off + 2 * i)[0]
             for i in range(n)]
    return SectSum(seq=header.seq, section_id=section_id,
                   active_nodes=active, packet_count=packets,
                   delay_p50_s=p50, delay_p90_s=p90, origin=header.origin,
                   route_stubs=stubs)


# --------------------------------------------------------------------------
# ROUTE (0x5303)
# --------------------------------------------------------------------------

@dataclass
class Route:
    seq: int
    section_id: int
    route_id: int
    packet_count: int
    delay_med_s: int
    last_heard_min: int
    origin: int = 0
    prefixes: List[int] = field(default_factory=list)  # 1 byte each


def encode_route(r: Route) -> bytes:
    if len(r.prefixes) > 255:
        raise CodecError("too many prefixes")
    body = pack_header(r.seq, r.origin)
    body += struct.pack(
        "<BHHHHB",
        _check_section_id(r.section_id, "section_id"),
        _u16(r.route_id, "route_id"),
        _u16(r.packet_count, "packet_count"),
        _u16(r.delay_med_s, "delay_med_s"),
        _u16(r.last_heard_min, "last_heard_min"),
        len(r.prefixes),
    )
    for pfx in r.prefixes:
        body += struct.pack("<B", _u8(pfx, "prefix"))
    return data_type_bytes(TYPE_ROUTE, body)


def decode_route(payload: bytes) -> Route:
    header, off = unpack_header(payload)
    if len(payload) < off + 10:
        raise CodecError("ROUTE too short")
    section_id, route_id, packets, delay, last, n = \
        struct.unpack_from("<BHHHHB", payload, off)
    _check_section_id(section_id, "decoded section_id")
    off += 10
    if len(payload) < off + n:
        raise CodecError("ROUTE prefixes truncated")
    prefixes = [payload[off + i] for i in range(n)]
    return Route(seq=header.seq, section_id=section_id, route_id=route_id,
                 packet_count=packets, delay_med_s=delay,
                 last_heard_min=last, origin=header.origin,
                 prefixes=prefixes)


# --------------------------------------------------------------------------
# INTRO (0x5304)
# --------------------------------------------------------------------------

@dataclass
class IntroEntry:
    prefix: int
    name: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    node_class: int = NODE_CLASS_UNKNOWN

    @property
    def flags(self) -> int:
        flags = 0
        if self.name:
            flags |= 0x01
        if self.lat is not None and self.lon is not None:
            flags |= 0x02
        flags |= (self.node_class & NODE_CLASS_MASK) << NODE_CLASS_SHIFT
        return flags


@dataclass
class Intro:
    seq: int = 0
    origin: int = 0
    entries: List[IntroEntry] = field(default_factory=list)
    # Deltas are relative to the LAYOUT centre/span (set by the builder);
    # the codec needs them to encode, and returns them on decode.
    center_lat: float = 0.0
    center_lon: float = 0.0
    span_m: float = 40000.0
    # THE SPAN RIDES ON THE WIRE (2026-09-23, Brett's "new set of offset
    # dots on every connect"): INTRO positions are deltas measured
    # against a map span, but v1.0-1.4 carried no span - the client
    # GUESSED it from whatever LAYOUT it held, and a mismatch (a sized
    # window, a replayed LAYOUT at connect) scaled every delta wrong.
    # v1.5: 2 LE meters. encode writes it; decode uses it as the truth
    # (opts.spanM, when given, is only cross-checked). 2.783 m of
    # position quantization at 60 km - far below GPS noise.
    wire_span_m: Optional[int] = None


def _position_deltas(intro: Intro, lat: float, lon: float) -> Tuple[int, int]:
    span_deg = intro.span_m / 111320.0
    dlat = round((lat - intro.center_lat) / span_deg * 32767)
    dlon = round((lon - intro.center_lon) / span_deg * 32767)
    # NEVER PIN (Brett's hard rule 2, 2026-09-26): a delta past the
    # end of the ruler used to be clamped to its end - a FABRICATED
    # position (the pile-of-dots ring the 60 km view exposed). A
    # ruler that cannot reach a node is a builder bug, and the honest
    # answer is the loud one: refuse to mint the packet at all.
    if not -32767 <= dlat <= 32767 or not -32767 <= dlon <= 32767:
        raise CodecError(
            f"position ({lat}, {lon}) falls outside the intro ruler "
            f"({intro.span_m} m) - widen the ruler; "
            f"never pin a fake position")
    return dlat, dlon


def _position_from_deltas(intro: Intro, dlat: int, dlon: int) -> Tuple[float, float]:
    span_deg = intro.span_m / 111320.0
    return (intro.center_lat + dlat / 32767.0 * span_deg,
            intro.center_lon + dlon / 32767.0 * span_deg)


def encode_intro(i: Intro) -> bytes:
    if len(i.entries) > 255:
        raise CodecError("too many intro entries")
    span_wire = round(i.span_m)
    if not 0 < span_wire <= 0xFFFFFF:
        raise CodecError(f"intro span_m out of wire range: {i.span_m}")
    body = pack_header(i.seq, i.origin, version=PROTO_VERSION_INTRO)
    # v1.6 (Brett, 2026-09-26): the span field IS THE RULER and grew
    # to 3 LE bytes - the old 2-byte meters field capped at 65.5 km
    # and pinned every farther node at its end. Old decoders refuse
    # v1.6 packets loudly (their version check), never silently wrong.
    body += span_wire.to_bytes(3, "little")
    body += struct.pack("<B", len(i.entries))
    for entry in i.entries:
        name_bytes = (entry.name or "").encode("utf-8")[:MAX_NAME]
        body += struct.pack("<BB", _u8(entry.prefix, "prefix"),
                            entry.flags)
        body += struct.pack("<B", len(name_bytes))
        if name_bytes:
            body += name_bytes
        if entry.flags & 0x02:
            dlat, dlon = _position_deltas(i, entry.lat, entry.lon)
            body += struct.pack("<hh", dlat, dlon)
    return data_type_bytes(TYPE_INTRO, body)


def decode_intro(payload: bytes, *, center_lat: float = 0.0,
                 center_lon: float = 0.0,
                 span_m: Optional[float] = None) -> Intro:
    """Decode INTRO. Positions are reconstructed from deltas against
    the span THE PACKET CARRIES (since v1.5) and the LAYOUT center the
    client already has (pass it here).

    span_m: a fallback ONLY for pre-v1.5 packets (nothing on the
    wire to trust). v1.6 (2026-09-26): the span is THE RULER - the
    scale measured to REACH every node in the packet (3 LE meters),
    so no position is ever pinned at a window edge and none is ever
    dropped. The old span cross-check is gone: the packet's span is
    the truth, and comparing a ruler to a LAYOUT window is noise."""
    header, off = unpack_header(payload)
    if header.version >= 0x06:
        # v1.6: the ruler, 3 LE meters.
        if len(payload) < off + 3:
            raise CodecError("INTRO too short for span field")
        wire_span = int.from_bytes(payload[off:off + 3], "little")
        off += 3
        if wire_span <= 0:
            raise CodecError(f"INTRO span must be positive, got {wire_span}")
    elif header.version >= 0x05:
        # v1.5: 2 LE meters (packets still in flight from an old host).
        if len(payload) < off + 2:
            raise CodecError("INTRO too short for span field")
        wire_span = struct.unpack_from("<H", payload, off)[0]
        off += 2
        if wire_span <= 0:
            raise CodecError(f"INTRO span must be positive, got {wire_span}")
    else:
        # v1.0-1.4 packets carry NO span (the old guess-field): fall
        # back to the caller's span, or the era's 40 km assumption -
        # exactly the behavior that produced Brett's offset-dots bug,
        # kept ONLY for packets still in flight from a pre-v1.5 host.
        wire_span = round(span_m) if span_m is not None else 40000
        if wire_span <= 0:
            raise CodecError(f"INTRO span must be positive, got {wire_span}")
    count = payload[off]
    off += 1
    intro = Intro(seq=header.seq, origin=header.origin,
                  center_lat=center_lat, center_lon=center_lon,
                  span_m=float(wire_span),
                  wire_span_m=wire_span if header.version >= 0x05 else None)
    for _ in range(count):
        if len(payload) < off + 3:
            raise CodecError("INTRO entry truncated")
        prefix, flags = struct.unpack_from("<BB", payload, off)
        name_len = payload[off + 2]
        off += 3
        node_class = (flags >> NODE_CLASS_SHIFT) & NODE_CLASS_MASK
        name = None
        if flags & 0x01:
            if len(payload) < off + name_len:
                raise CodecError("INTRO name truncated")
            name = payload[off:off + name_len].decode("utf-8", "replace")
        off += name_len
        lat = lon = None
        if flags & 0x02:
            if len(payload) < off + 4:
                raise CodecError("INTRO position truncated")
            dlat, dlon = struct.unpack_from("<hh", payload, off)
            off += 4
            lat, lon = _position_from_deltas(
                Intro(center_lat=center_lat, center_lon=center_lon,
                      span_m=float(wire_span)), dlat, dlon)  # noqa: E501
        intro.entries.append(IntroEntry(prefix=prefix, name=name,
                                        lat=lat, lon=lon,
                                        node_class=node_class))
    return intro


# --------------------------------------------------------------------------
# LAYOUT (0x5305)
#
# v1.6 (Brett, 2026-09-25): the section grid is no longer square -
# `grid` is the ACROSS count and a `rows` byte (down count) rides at
# the END of the body. A packet WITHOUT it is legacy square
# (grid x grid). Old decoders skip it happily (they never looked at
# trailing bytes), so one wire serves both.
# --------------------------------------------------------------------------

@dataclass
class Layout:
    seq: int
    grid: int            # sections ACROSS (columns)
    center_lat: float
    center_lon: float
    span_m: int
    origin: int = 0
    name: str = ""
    rows: int = 0        # sections DOWN; 0 = legacy square (grid x grid)


def encode_layout(l: Layout) -> bytes:
    if not 2 <= l.grid <= 5:
        raise CodecError(f"grid out of range: {l.grid}")
    rows = l.rows if l.rows > 0 else l.grid
    if not 2 <= rows <= 5:
        raise CodecError(f"rows out of range: {rows}")
    name_bytes = l.name.encode("utf-8")[:MAX_NAME]
    body = pack_header(l.seq, l.origin)
    body += struct.pack("<B", l.grid)
    body += struct.pack("<ii", round(l.center_lat * 1e6),
                        round(l.center_lon * 1e6))
    body += struct.pack("<H", _u16(l.span_m, "span_m"))
    body += struct.pack("<B", len(name_bytes))
    body += name_bytes
    body += struct.pack("<B", rows)  # v1.6: AFTER the name (legacy-safe)
    return data_type_bytes(TYPE_LAYOUT, body)


def decode_layout(payload: bytes) -> Layout:
    header, off = unpack_header(payload)
    if len(payload) < off + 8:
        raise CodecError("LAYOUT too short")
    grid = payload[off]
    off += 1
    lat_e6, lon_e6 = struct.unpack_from("<ii", payload, off)
    off += 8
    span_m = struct.unpack_from("<H", payload, off)[0]
    off += 2
    if len(payload) < off + 1:
        raise CodecError("LAYOUT name length missing")
    name_len = payload[off]
    off += 1
    if len(payload) < off + name_len:
        raise CodecError("LAYOUT name truncated")
    name = payload[off:off + name_len].decode("utf-8", "replace")
    off += name_len
    # v1.6 trailing rows byte; absent = legacy square (grid x grid).
    rows = grid
    if len(payload) > off:
        rows = payload[off]
        if not 2 <= rows <= 5:
            raise CodecError(f"LAYOUT rows out of range: {rows}")
    return Layout(seq=header.seq, grid=grid, center_lat=lat_e6 / 1e6,
                  center_lon=lon_e6 / 1e6, span_m=span_m,
                  origin=header.origin, name=name, rows=rows)


# --------------------------------------------------------------------------
# SNAP (0x5306)
# --------------------------------------------------------------------------

@dataclass
class Snap:
    seq: int
    snap_id: int
    part: int
    parts: int
    body: bytes
    origin: int = 0


def encode_snap(s: Snap) -> bytes:
    if len(s.body) > 255:
        raise CodecError(f"SNAP body too long: {len(s.body)}")
    body = pack_header(s.seq, s.origin)
    body += struct.pack("<BBB", _u8(s.snap_id, "snap_id"),
                        _u8(s.part, "part"), _u8(s.parts, "parts"))
    body += s.body
    return data_type_bytes(TYPE_SNAP, body)


def decode_snap(payload: bytes) -> Snap:
    header, off = unpack_header(payload)
    if len(payload) < off + 3:
        raise CodecError("SNAP too short")
    snap_id, part, parts = struct.unpack_from("<BBB", payload, off)
    off += 3
    return Snap(seq=header.seq, snap_id=snap_id, part=part, parts=parts,
                origin=header.origin, body=bytes(payload[off:]))


# --------------------------------------------------------------------------
# REFRESH_REQ (0x5311) - client -> host
# --------------------------------------------------------------------------

@dataclass
class RefreshReq:
    seq: int
    kind: int          # 1 = section, 2 = route
    target: int        # section_id or route_id
    nonce: int
    origin: int = 0    # client's own 2-byte id (v1.1)
    host: int = REFRESH_HOST_ANY  # preferred origin, 0 = owner decides
    # v1.3: the window the client wants, in km (20/40/60). 0 = host
    # decides = the whole 60x60 home box (today's behavior, and what
    # every pre-v1.3 encoder means when it omits the field).
    span_km: int = REFRESH_SPAN_HOST_DECIDES
    # v1.6 (vectored sync): the client's change-counter marker; the
    # answer ships full records only for nodes changed after it.
    # 0 = "not vectored" = the full roster (today's behavior).
    sync_marker: int = 0


def encode_refresh_req(r: RefreshReq) -> bytes:
    if r.kind not in (REFRESH_KIND_SECTION, REFRESH_KIND_ROUTE):
        raise CodecError(f"refresh kind invalid: {r.kind}")
    body = pack_header(r.seq, r.origin, version=PROTO_VERSION_REFRESH)
    body += struct.pack("<BHHH", r.kind, _u16(r.target, "target"),
                        _u16(r.host, "host"), _u16(r.nonce, "nonce"))
    # v1.3 (0x04): + span_km(2 LE). The version byte in the header is
    # what tells an old decoder "this body is longer than you think" -
    # and a strict old decoder REJECTS it loudly rather than misreads
    # (the same rule that guards unknown versions against us).
    body += struct.pack("<H", _u16(r.span_km, "span_km"))
    # v1.6 (0x06): + sync_marker(2 LE) - 0 = not vectored.
    body += struct.pack("<H", _u16(r.sync_marker, "sync_marker"))
    return data_type_bytes(TYPE_REFRESH_REQ, body)


def decode_refresh_req(payload: bytes) -> RefreshReq:
    header, off = unpack_header(payload)
    if header.version >= 0x06:
        # v1.6 body: kind(1) target(2) host(2) nonce(2) span_km(2)
        #             sync_marker(2)
        if len(payload) < off + 11:
            raise CodecError("REFRESH_REQ too short")
        kind, target, host = struct.unpack_from("<BHH", payload, off)
        nonce, span_km = struct.unpack_from("<HH", payload, off + 5)
        sync_marker = struct.unpack_from("<H", payload, off + 9)[0]
    elif header.version >= 0x04:
        # v1.3 body: kind(1) target(2) host(2) nonce(2) span_km(2)
        if len(payload) < off + 9:
            raise CodecError("REFRESH_REQ too short")
        kind, target, host = struct.unpack_from("<BHH", payload, off)
        nonce, span_km = struct.unpack_from("<HH", payload, off + 5)
        sync_marker = 0
    elif header.version >= 0x02:
        # v1.1 body: kind(1) target(2) host(2) nonce(2), no span_km
        if len(payload) < off + 7:
            raise CodecError("REFRESH_REQ too short")
        kind, target, host = struct.unpack_from("<BHH", payload, off)
        nonce = struct.unpack_from("<H", payload, off + 5)[0]
        span_km = REFRESH_SPAN_HOST_DECIDES
        sync_marker = 0
    else:
        # v1 body: kind(1) target(2) nonce(2), no host field
        if len(payload) < off + 5:
            raise CodecError("REFRESH_REQ too short")
        kind, target, nonce = struct.unpack_from("<BHH", payload, off)
        host = REFRESH_HOST_ANY
        span_km = REFRESH_SPAN_HOST_DECIDES
        sync_marker = 0
    return RefreshReq(seq=header.seq, kind=kind, target=target,
                      nonce=nonce, origin=header.origin, host=host,
                      span_km=span_km, sync_marker=sync_marker)


# --------------------------------------------------------------------------
# GONE (0x5312) - vectored sync deletion notice (v1.6)
# --------------------------------------------------------------------------

@dataclass
class Gone:
    seq: int
    origin: int = 0
    prefixes: List[int] = field(default_factory=list)  # 1 byte each


# --------------------------------------------------------------------------
# HEARTBEAT (0x5313) - the phone app's keep-alive (Brett's airtime rule)
# --------------------------------------------------------------------------

@dataclass
class Heartbeat:
    seq: int
    origin: int = 0


def encode_heartbeat(h: Heartbeat) -> bytes:
    """Header ONLY (5 bytes) inside the 3-byte type/len envelope: 8 bytes
    of plaintext, the smallest packet the format can carry. No body -
    nothing to decode wrong on either side."""
    return data_type_bytes(TYPE_HEARTBEAT, pack_header(h.seq, h.origin))


def decode_heartbeat(payload: bytes) -> Heartbeat:
    header, _off = unpack_header(payload)
    return Heartbeat(seq=header.seq, origin=header.origin)


def encode_gone(*, seq: int, origin: int = 0,
                prefixes: List[int]) -> bytes:
    if len(prefixes) > MAX_GONE_PER_PACKET:
        raise CodecError(f"too many gone prefixes: {len(prefixes)} "
                         f"> {MAX_GONE_PER_PACKET}")
    body = pack_header(seq, origin, version=PROTO_VERSION_GONE)
    body += struct.pack("<B", len(prefixes))
    for pfx in prefixes:
        body += struct.pack("<B", _u8(pfx, "gone prefix"))
    return data_type_bytes(TYPE_GONE, body)


def decode_gone(payload: bytes) -> Gone:
    header, off = unpack_header(payload)
    if len(payload) < off + 1:
        raise CodecError("GONE too short")
    n = payload[off]
    off += 1
    if len(payload) < off + n:
        raise CodecError("GONE prefixes truncated")
    prefixes = [payload[off + i] for i in range(n)]
    return Gone(seq=header.seq, origin=header.origin, prefixes=prefixes)


# --------------------------------------------------------------------------
# CLINIC (0x5314) - the mesh clinic's facts + provenance
# (CLINIC-WIRE.md governs these bytes; it was written BEFORE any of
# them were wired.)
#
# body = header(5) + count(1) + records; each record is
# kind(1) + len(1) + payload(len). The WHOLE plaintext stays within
# MAX_CHANNEL_DATA (163 B) so at most CLINIC_MAX_RECORDS ride at once.
# --------------------------------------------------------------------------

CLINIC_MAX_RECORDS = 7
CLINIC_MAX_NAME = 24          # peer intro names this wire can carry

CLINIC_KIND_NODE = 1
CLINIC_KIND_ROUTE = 2
CLINIC_KIND_FLAG = 3
CLINIC_KIND_PEER = 4

# Trouble flags (kind 3) - FACTS with evidence, never verdicts.
FLAG_SIG_FAIL = 1
FLAG_TS_BACKWARDS = 2
FLAG_RATE_STORM = 3
FLAG_CORRUPT_SHARE = 4

# Peer reports (kind 4) - what another box SAID (second-hand).
REPORT_PULSE = 1
REPORT_SECT_SUM = 2
REPORT_ROUTE = 3
REPORT_INTRO = 4

# Wire sentinels: missing stays missing, never a plausible constant.
AGE_UNKNOWN_MIN = 0xFFFF      # minute fields: older than the wire says
SHARE_UNKNOWN_PCT = 255       # node fact: no identified traffic counted
SIGNAL_UNKNOWN = -128         # i8 signal stats: no samples (radio never
                              # reports -128 dBm / -32 dB - not receivable)
SIGNAL_SD_UNKNOWN = 255       # u8 signal spread: fewer than 2 samples


@dataclass
class ClinicNodeFact:
    """Kind 1: one node's chart as THIS box heard it (20 B payload)."""
    source: int
    prefix: int
    last_age_min: int
    age_days: int
    strip: int                 # 24-bit: bit 0 oldest hour ... bit 23 now
    hops_typ: int              # typical radio hops (0 = unknown)
    share_pct: int             # of identified traffic, 24 h (255 = none)
    snr_ewma: int = SIGNAL_UNKNOWN
    snr_best: int = SIGNAL_UNKNOWN
    snr_worst: int = SIGNAL_UNKNOWN
    snr_sd: int = SIGNAL_SD_UNKNOWN
    rssi_ewma: int = SIGNAL_UNKNOWN
    rssi_best: int = SIGNAL_UNKNOWN
    rssi_worst: int = SIGNAL_UNKNOWN
    rssi_sd: int = SIGNAL_SD_UNKNOWN


@dataclass
class ClinicRouteFact:
    """Kind 2: one route's chart (delay 0 = unknown, honest stamps only)."""
    source: int
    path: Tuple[int, ...]      # repeater trail, travel order (1..8)
    uses: int
    direct: int                # 1 = heard straight from the sender
    delay_min_s: int
    delay_med_s: int
    delay_max_s: int
    last_age_min: int
    age_days: int


@dataclass
class ClinicFlagFact:
    """Kind 3: one trouble flag - what was measured, not a verdict."""
    source: int
    flag: int                  # FLAG_*
    subject: int               # key prefix; 0 = mesh-wide (corrupt share)
    events: int
    first_age_min: int
    last_age_min: int
    detail: int                # worst jump s / peak packets-per-min / per-mille


@dataclass
class ClinicPeerFact:
    """Kind 4: what a peer box said (source = the peer, never us)."""
    source: int
    report: int                # REPORT_*
    subject: int               # 0 / section id / route id / node prefix
    heard_age_min: int
    values: Tuple[int, int, int, int] = (0, 0, 0, 0)
    path: Tuple[int, ...] = ()
    cls: int = 0
    lat: Optional[float] = None   # None = the peer reported no position
    lon: Optional[float] = None
    name: str = ""


@dataclass
class Clinic:
    seq: int
    origin: int
    records: List[object] = field(default_factory=list)


def _i8(value: int, what: str) -> int:
    value = int(value)
    if not -128 <= value <= 127:
        raise CodecError(f"{what} out of range: {value}")
    return value


def _age_minutes(seconds: float) -> int:
    """Minutes since, on the wire: capped at AGE_UNKNOWN_MIN (never a
    wrapped-around small number pretending to be fresh)."""
    minutes = int(seconds // 60)
    if minutes < 0:
        return 0
    return AGE_UNKNOWN_MIN if minutes > AGE_UNKNOWN_MIN else minutes


def clinic_sort_key(record: object) -> tuple:
    """Deterministic fact order - the cursor walk stays stable across
    batches so every fact cycles through the rotating slice."""
    if isinstance(record, ClinicNodeFact):
        return (CLINIC_KIND_NODE, record.prefix, record.source, ())
    if isinstance(record, ClinicRouteFact):
        return (CLINIC_KIND_ROUTE, 0, record.source, tuple(record.path))
    if isinstance(record, ClinicFlagFact):
        return (CLINIC_KIND_FLAG, record.flag, record.source,
                (record.subject,))
    if isinstance(record, ClinicPeerFact):
        return (CLINIC_KIND_PEER, record.report, record.source,
                (record.subject,))
    raise CodecError(f"unknown clinic record {type(record).__name__}")


def encode_clinic_record(record: object) -> bytes:
    """One record: kind(1) + len(1) + payload. Raises loudly when the
    wire cannot carry the truth (never pins, never fabricates)."""
    if isinstance(record, ClinicNodeFact):
        strip = int(record.strip)
        if not 0 <= strip <= 0xFFFFFF:
            raise CodecError(f"node strip out of range: {strip}")
        payload = struct.pack(
            "<HB",
            _u16(record.source, "node source"),
            _u8(record.prefix, "node prefix"),
        )
        payload += struct.pack(
            "<HH",
            _u16(record.last_age_min, "node last_age_min"),
            _u16(record.age_days, "node age_days"),
        )
        payload += strip.to_bytes(3, "little")
        payload += struct.pack(
            "<BB",
            _u8(record.hops_typ, "node hops_typ"),
            _u8(record.share_pct, "node share_pct"),
        )
        payload += struct.pack(
            "<bbbB",
            _i8(record.snr_ewma, "snr_ewma"),
            _i8(record.snr_best, "snr_best"),
            _i8(record.snr_worst, "snr_worst"),
            _u8(record.snr_sd, "snr_sd"),
        )
        payload += struct.pack(
            "<bbbB",
            _i8(record.rssi_ewma, "rssi_ewma"),
            _i8(record.rssi_best, "rssi_best"),
            _i8(record.rssi_worst, "rssi_worst"),
            _u8(record.rssi_sd, "rssi_sd"),
        )
    elif isinstance(record, ClinicRouteFact):
        path = tuple(record.path)
        if not 1 <= len(path) <= 8:
            raise CodecError(f"route fact path length {len(path)} "
                             "outside 1..8")
        payload = struct.pack("<H", _u16(record.source, "route source"))
        payload += struct.pack("<B", len(path))
        payload += bytes(_u8(p, "route path byte") for p in path)
        payload += struct.pack(
            "<HBHHHH",
            _u16(record.uses, "route uses"),
            _u8(record.direct, "route direct"),
            _u16(record.delay_min_s, "route delay_min_s"),
            _u16(record.delay_med_s, "route delay_med_s"),
            _u16(record.delay_max_s, "route delay_max_s"),
            _u16(record.last_age_min, "route last_age_min"),
        )
        payload += struct.pack("<H", _u16(record.age_days, "route age_days"))
    elif isinstance(record, ClinicFlagFact):
        payload = struct.pack(
            "<HBBHHHH",
            _u16(record.source, "flag source"),
            _u8(record.flag, "flag kind"),
            _u8(record.subject, "flag subject"),
            _u16(record.events, "flag events"),
            _u16(record.first_age_min, "flag first_age_min"),
            _u16(record.last_age_min, "flag last_age_min"),
            _u16(record.detail, "flag detail"),
        )
    elif isinstance(record, ClinicPeerFact):
        payload = struct.pack(
            "<HBHH",
            _u16(record.source, "peer source"),
            _u8(record.report, "peer report"),
            _u16(record.subject, "peer subject"),
            _u16(record.heard_age_min, "peer heard_age_min"),
        )
        v1, v2, v3, v4 = (int(v) for v in record.values)
        if record.report in (REPORT_PULSE, REPORT_SECT_SUM):
            payload += struct.pack("<HHHH", _u16(v1, "peer v1"),
                                   _u16(v2, "peer v2"), _u16(v3, "peer v3"),
                                   _u16(v4, "peer v4"))
        elif record.report == REPORT_ROUTE:
            path = tuple(record.path)
            if not 1 <= len(path) <= 8:
                raise CodecError(f"peer route path length {len(path)} "
                                 "outside 1..8")
            payload += struct.pack("<HHH", _u16(v1, "peer uses"),
                                   _u16(v2, "peer delay_med"),
                                   _u16(v3, "peer last_age"))
            payload += struct.pack("<B", len(path))
            payload += bytes(_u8(p, "peer path byte") for p in path)
        elif record.report == REPORT_INTRO:
            name_bytes = (record.name or "").encode("utf-8")
            if len(name_bytes) > CLINIC_MAX_NAME:
                raise CodecError(
                    f"peer intro name longer than {CLINIC_MAX_NAME} B "
                    "- refuse to mint, never truncate a name")
            lat_e7 = 0 if record.lat is None else int(round(record.lat * 1e7))
            lon_e7 = 0 if record.lon is None else int(round(record.lon * 1e7))
            # 0/0 = NO POSITION (the node table's own null-island rule).
            if not -(2 ** 31) <= lat_e7 <= 2 ** 31 - 1 \
                    or not -(2 ** 31) <= lon_e7 <= 2 ** 31 - 1:
                raise CodecError("peer intro position out of e7 range")
            payload += struct.pack("<BiiB", _u8(record.cls, "peer class"),
                                   lat_e7, lon_e7, len(name_bytes))
            payload += name_bytes
        else:
            raise CodecError(f"unknown peer report kind {record.report}")
    else:
        raise CodecError(f"unknown clinic record {type(record).__name__}")
    if len(payload) > 255:
        raise CodecError(f"clinic record too long: {len(payload)} B")
    return struct.pack("<BB", _clinic_kind(record), len(payload)) + payload


def _clinic_kind(record: object) -> int:
    if isinstance(record, ClinicNodeFact):
        return CLINIC_KIND_NODE
    if isinstance(record, ClinicRouteFact):
        return CLINIC_KIND_ROUTE
    if isinstance(record, ClinicFlagFact):
        return CLINIC_KIND_FLAG
    if isinstance(record, ClinicPeerFact):
        return CLINIC_KIND_PEER
    raise CodecError(f"unknown clinic record {type(record).__name__}")


def _decode_clinic_record(payload: bytes, off: int) -> Tuple[object, int]:
    if len(payload) < off + 2:
        raise CodecError("CLINIC record truncated (kind/len)")
    kind = payload[off]
    length = payload[off + 1]
    off += 2
    if len(payload) < off + length:
        raise CodecError("CLINIC record truncated (payload)")
    body = payload[off:off + length]
    off += length
    if kind == CLINIC_KIND_NODE:
        if len(body) != 20:
            raise CodecError(f"CLINIC node fact must be 20 B, got {len(body)}")
        source = struct.unpack_from("<H", body, 0)[0]
        prefix = body[2]
        last_age, age_days = struct.unpack_from("<HH", body, 3)
        strip = int.from_bytes(body[7:10], "little")
        hops, share = body[10], body[11]
        snr_e, snr_b, snr_w = struct.unpack_from("<bbb", body, 12)
        snr_sd = body[15]
        rssi_e, rssi_b, rssi_w = struct.unpack_from("<bbb", body, 16)
        rssi_sd = body[19]
        return ClinicNodeFact(
            source=source, prefix=prefix, last_age_min=last_age,
            age_days=age_days, strip=strip, hops_typ=hops, share_pct=share,
            snr_ewma=snr_e, snr_best=snr_b, snr_worst=snr_w, snr_sd=snr_sd,
            rssi_ewma=rssi_e, rssi_best=rssi_b, rssi_worst=rssi_w,
            rssi_sd=rssi_sd), off
    if kind == CLINIC_KIND_ROUTE:
        if len(body) < 3:
            raise CodecError("CLINIC route fact too short")
        source = struct.unpack_from("<H", body, 0)[0]
        path_len = body[2]
        if not 1 <= path_len <= 8 or len(body) != 3 + path_len + 13:
            raise CodecError("CLINIC route fact malformed")
        path = tuple(body[3:3 + path_len])
        uses, direct, dmin, dmed, dmax, last_age = struct.unpack_from(
            "<HBHHHH", body, 3 + path_len)
        age_days = struct.unpack_from("<H", body, 3 + path_len + 11)[0]
        return ClinicRouteFact(
            source=source, path=path, uses=uses, direct=direct,
            delay_min_s=dmin, delay_med_s=dmed, delay_max_s=dmax,
            last_age_min=last_age, age_days=age_days), off
    if kind == CLINIC_KIND_FLAG:
        if len(body) != 12:
            raise CodecError(f"CLINIC flag must be 12 B, got {len(body)}")
        (source, flag, subject, events, first_age, last_age,
         detail) = struct.unpack("<HBBHHHH", body)
        return ClinicFlagFact(
            source=source, flag=flag, subject=subject, events=events,
            first_age_min=first_age, last_age_min=last_age,
            detail=detail), off
    if kind == CLINIC_KIND_PEER:
        if len(body) < 7:
            raise CodecError("CLINIC peer report too short")
        source, report, subject, heard_age = struct.unpack_from(
            "<HBHH", body, 0)
        rest = body[7:]
        values = (0, 0, 0, 0)
        path: Tuple[int, ...] = ()
        cls = 0
        lat = lon = None
        name = ""
        if report in (REPORT_PULSE, REPORT_SECT_SUM):
            if len(rest) != 8:
                raise CodecError("CLINIC peer numbers must be 8 B")
            values = struct.unpack("<HHHH", rest)
        elif report == REPORT_ROUTE:
            if len(rest) < 7:
                raise CodecError("CLINIC peer route too short")
            v1, v2, v3 = struct.unpack_from("<HHH", rest, 0)
            path_len = rest[6]
            if not 1 <= path_len <= 8 or len(rest) != 7 + path_len:
                raise CodecError("CLINIC peer route malformed")
            values = (v1, v2, v3, 0)
            path = tuple(rest[7:7 + path_len])
        elif report == REPORT_INTRO:
            if len(rest) < 10:
                raise CodecError("CLINIC peer intro too short")
            cls, lat_e7, lon_e7, name_len = struct.unpack_from("<BiiB", rest, 0)
            if len(rest) != 10 + name_len:
                raise CodecError("CLINIC peer intro name malformed")
            if name_len:
                try:
                    name = rest[10:10 + name_len].decode("utf-8")
                except UnicodeDecodeError as exc:
                    raise CodecError(f"CLINIC peer name not UTF-8: {exc}")
            # 0/0 = the peer reported NO position (null-island rule).
            lat = None if lat_e7 == 0 and lon_e7 == 0 else lat_e7 / 1e7
            lon = None if lat is None else lon_e7 / 1e7
        else:
            raise CodecError(f"unknown peer report kind {report}")
        return ClinicPeerFact(
            source=source, report=report, subject=subject,
            heard_age_min=heard_age, values=values, path=path, cls=cls,
            lat=lat, lon=lon, name=name), off
    raise CodecError(f"unknown CLINIC record kind {kind}")


def encode_clinic(records: List[object], *, seq: int,
                  origin: int = 0) -> bytes:
    """Full CLINIC plaintext (with envelope). Hard caps from the wire
    page: at most 7 records, whole plaintext <= MAX_CHANNEL_DATA."""
    if len(records) > CLINIC_MAX_RECORDS:
        raise CodecError(f"too many clinic records: {len(records)} > "
                         f"{CLINIC_MAX_RECORDS}")
    body = pack_header(seq, origin)
    body += struct.pack("<B", len(records))
    for record in records:
        body += encode_clinic_record(record)
    plaintext = data_type_bytes(TYPE_CLINIC, body)
    if len(plaintext) > MAX_CHANNEL_DATA:
        raise CodecError(f"clinic packet {len(plaintext)} B exceeds "
                         f"the {MAX_CHANNEL_DATA} B channel cap")
    return plaintext


def decode_clinic(payload: bytes) -> Clinic:
    """Decode a CLINIC body (envelope already stripped)."""
    header, off = unpack_header(payload)
    if len(payload) < off + 1:
        raise CodecError("CLINIC too short (count)")
    count = payload[off]
    off += 1
    records: List[object] = []
    for _ in range(count):
        record, off = _decode_clinic_record(payload, off)
        records.append(record)
    return Clinic(seq=header.seq, origin=header.origin, records=records)


# --------------------------------------------------------------------------
# Generic decode + helpers
# --------------------------------------------------------------------------

def peek_data_type(payload: bytes) -> int:
    """The data_type of a full GRP_DATA plaintext (before decoding)."""
    if len(payload) < 3:
        raise CodecError("payload too short for data_type")
    return struct.unpack_from("<H", payload, 0)[0]


def decode_any(payload: bytes) -> object:
    """Decode any scope packet by its data_type. A v1.5+ INTRO decodes
    by its OWN carried span (no caller knowledge needed)."""
    data_type = peek_data_type(payload)
    return decode_body(data_type, payload[3:])


def decode_body(data_type: int, body: bytes) -> object:
    """Decode a scope BODY whose 3-byte type/len envelope is already
    stripped (what the companion delivers in CHANNEL_DATA_RECV: the
    radio decrypts and removes its own framing before queueing -
    meshcore reader.py sets payload = data_len bytes; openhop_core
    companion_base._handle_group_data_packet queues blob =
    plaintext[3:3+data_len])."""
    if data_type == TYPE_PULSE:
        return decode_pulse(body)
    if data_type == TYPE_SECT_SUM:
        return decode_sect_sum(body)
    if data_type == TYPE_ROUTE:
        return decode_route(body)
    if data_type == TYPE_INTRO:
        return decode_intro(body)
    if data_type == TYPE_LAYOUT:
        return decode_layout(body)
    if data_type == TYPE_SNAP:
        return decode_snap(body)
    if data_type == TYPE_REFRESH_REQ:
        return decode_refresh_req(body)
    if data_type == TYPE_GONE:
        return decode_gone(body)
    if data_type == TYPE_HEARTBEAT:
        return decode_heartbeat(body)
    if data_type == TYPE_CLINIC:
        return decode_clinic(body)
    raise CodecError(f"unknown data_type {data_type:#06x}")


# --------------------------------------------------------------------------
# Range guards
# --------------------------------------------------------------------------

def _u8(value: int, what: str) -> int:
    value = int(value)
    if not 0 <= value <= 0xFF:
        raise CodecError(f"{what} out of range: {value}")
    return value


def _u16(value: int, what: str) -> int:
    value = int(value)
    if not 0 <= value <= 0xFFFF:
        raise CodecError(f"{what} out of range: {value}")
    return value
