"""Wire codec for the scope feed protocol v1.

Implements PROTOCOL.md exactly. The TypeScript port
(scope-app/src/lib/codec.ts) must stay byte-compatible and pass the
same golden vectors (tests/test_codec.py, generated by
tools/gen_golden.py).

All multi-byte integers are little-endian (MeshCore convention).
"""
from __future__ import annotations

import struct
from dataclasses import dataclass, field
from typing import List, Optional, Tuple

# v1.1 (0x02): + origin in header, + refresh host target.
# v1.2 (0x03, 2026-09-20): SECTION IDS ARE 1-BASED on the wire
# (1 = NW .. 9 = SE, matching what the app prints). 0 is RESERVED and
# means "whole-area" in a REFRESH_REQ target; a SECT_SUM/ROUTE with
# section_id 0 is malformed and rejected at decode. Header layout is
# unchanged from v1.1 (version + seq + origin).
# v1.3 (0x04, 2026-09-23, MAP-SIZE-DESIGN.md): REFRESH_REQ gains an
# optional span_km field (2 LE, kilometres) so a client can ask for a
# 20/40/60 km window of the host's 60x60 home area. 0 = host decides
# (= the whole home box, today's behavior). Older encoders that omit
# the field decode as span_km=0. Header layout unchanged.
PROTO_VERSION = 0x04

# Allowed client window sizes for a refresh (MAP-SIZE-DESIGN section
# 4): 0 = host decides. The snap-to-nearest choice lives in the
# callers (config/service), not the codec - the wire just carries the
# number.
REFRESH_SPAN_HOST_DECIDES = 0

# REFRESH_REQ target 0 = WHOLE-AREA refresh (any kind): the answer is
# LAYOUT + one summary per section + node names. Section targets are
# 1..grid*grid. Never a square: that is the whole point (Brett
# 2026-09-20 - "section 0" in a log confused humans and it also meant
# the wire could not say "the whole map" and "upper-left" apart).
REFRESH_WHOLE_AREA = 0

# data_type values (the 0x53 magic marks scope traffic)
TYPE_PULSE = 0x5301
TYPE_SECT_SUM = 0x5302
TYPE_ROUTE = 0x5303
TYPE_INTRO = 0x5304
TYPE_LAYOUT = 0x5305
TYPE_SNAP = 0x5306
TYPE_REFRESH_REQ = 0x5311

TYPE_NAMES = {
    TYPE_PULSE: "PULSE",
    TYPE_SECT_SUM: "SECT_SUM",
    TYPE_ROUTE: "ROUTE",
    TYPE_INTRO: "INTRO",
    TYPE_LAYOUT: "LAYOUT",
    TYPE_SNAP: "SNAP",
    TYPE_REFRESH_REQ: "REFRESH_REQ",
}

# CMD_SEND_CHANNEL_DATA payload budget (openhop_core constants.py:
# MAX_FRAME_SIZE 172 - 9). We target <= 120 bytes of plaintext.
MAX_CHANNEL_DATA = 163
TARGET_PAYLOAD = 120

# LAYOUT/INTRO name length cap
MAX_NAME = 31

REFRESH_KIND_SECTION = 1
REFRESH_KIND_ROUTE = 2
REFRESH_HOST_ANY = 0x0000   # "owner decides" (v1.1 election)

# INTRO flags bits 2-3: node class (v1.1). 0 = unknown (the honest
# default when the host's source data does not classify nodes).
NODE_CLASS_UNKNOWN = 0x00
NODE_CLASS_REPEATER = 0x01
NODE_CLASS_COMPANION = 0x02
NODE_CLASS_RESERVED = 0x03
NODE_CLASS_SHIFT = 2
NODE_CLASS_MASK = 0x03


class CodecError(Exception):
    """Raised when a payload cannot be decoded; message says why."""


# --------------------------------------------------------------------------
# Header helpers
# --------------------------------------------------------------------------

def pack_header(seq: int, origin: int = 0) -> bytes:
    """proto_version(1) + seq(2 LE) + origin(2 LE).

    origin = first 2 bytes of the host's pubkey - identifies the sender
    when several scope hosts share the channel (v1.1). v1 compat: the
    decoder maps version-0x01 3-byte headers to origin 0x0000.
    """
    if not 0 <= int(seq) <= 0xFFFF:
        raise CodecError(f"seq out of range: {seq}")
    if not 0 <= int(origin) <= 0xFFFF:
        raise CodecError(f"origin out of range: {origin}")
    return struct.pack("<BHH", PROTO_VERSION, int(seq), int(origin))


@dataclass
class Header:
    version: int
    seq: int
    origin: int = 0


def unpack_header(payload: bytes, offset: int = 0) -> Tuple[Header, int]:
    if len(payload) < offset + 3:
        raise CodecError("payload too short for header")
    version = payload[offset]
    if version == 0x01:
        # v1 packet: 3-byte header, no origin field.
        seq = struct.unpack_from("<H", payload, offset + 1)[0]
        return Header(version=version, seq=seq, origin=0), offset + 3
    if version not in (0x02, 0x03, 0x04):
        # STRICT: an unknown version must not be silently read with the
        # wrong field widths (0x01 = 3-byte, 0x02+ = 5-byte). A loud
        # error beats a confident misread.
        raise CodecError(f"unsupported protocol version 0x{version:02x}")
    if len(payload) < offset + 5:
        raise CodecError("payload too short for v1.1 header")
    seq, origin = struct.unpack_from("<HH", payload, offset + 1)
    return Header(version=version, seq=seq, origin=origin), offset + 5


def data_type_bytes(data_type: int, body: bytes) -> bytes:
    """Full GRP_DATA plaintext: data_type(2 LE) + data_len(1) + body.

    data_len covers the header+body (everything after the data_type
    field), matching the companion framing.
    """
    if not 0 <= data_type <= 0xFFFF:
        raise CodecError(f"data_type out of range: {data_type:#x}")
    if len(body) > 255:
        raise CodecError(f"body too long: {len(body)} > 255")
    return struct.pack("<HB", data_type, len(body)) + body


# --------------------------------------------------------------------------
# PULSE (0x5301)
# --------------------------------------------------------------------------

@dataclass
class Pulse:
    seq: int
    uptime_min: int
    rx_per_hour: int
    feed_airtime_s_per_h: int
    active_total: int
    origin: int = 0
    section_counts: List[int] = field(default_factory=list)


def encode_pulse(p: Pulse) -> bytes:
    if len(p.section_counts) > 255:
        raise CodecError("too many sections")
    body = pack_header(p.seq, p.origin)
    body += struct.pack(
        "<HHHHB",
        _u16(p.uptime_min, "uptime_min"),
        _u16(p.rx_per_hour, "rx_per_hour"),
        _u16(p.feed_airtime_s_per_h, "feed_airtime_s_per_h"),
        _u16(p.active_total, "active_total"),
        len(p.section_counts),
    )
    for count in p.section_counts:
        body += struct.pack("<B", _u8(count, "section count"))
    return data_type_bytes(TYPE_PULSE, body)


def decode_pulse(payload: bytes) -> Pulse:
    header, off = unpack_header(payload)
    if len(payload) < off + 9:
        raise CodecError("PULSE too short")
    uptime, rx, air, total, n = struct.unpack_from("<HHHHB", payload, off)
    off += 9
    if len(payload) - off < n:
        raise CodecError("PULSE section counts truncated")
    counts = [payload[off + i] for i in range(n)]
    return Pulse(seq=header.seq, uptime_min=uptime, rx_per_hour=rx,
                 feed_airtime_s_per_h=air, active_total=total,
                 origin=header.origin, section_counts=counts)


# --------------------------------------------------------------------------
# SECT_SUM (0x5302)
# --------------------------------------------------------------------------

@dataclass
class SectSum:
    seq: int
    section_id: int
    active_nodes: int
    packet_count: int
    delay_p50_s: int
    delay_p90_s: int
    origin: int = 0
    route_stubs: List[int] = field(default_factory=list)  # route_ids


def _check_section_id(value: int, where: str) -> int:
    """Wire section ids are 1-BASED (v1.2): 1..255 valid on the byte.

    0 is reserved (whole-area marker in REFRESH_REQ targets); a
    SECT_SUM/ROUTE carrying 0 is malformed - reject at the boundary
    instead of drawing a phantom NW square."""
    value = _u8(value, where)
    if value == REFRESH_WHOLE_AREA:
        raise CodecError(f"{where}: 0 is reserved (whole-area)")
    return value


def encode_sect_sum(s: SectSum) -> bytes:
    if len(s.route_stubs) > 255:
        raise CodecError("too many route stubs")
    body = pack_header(s.seq, s.origin)
    body += struct.pack(
        "<BBHHHBB",
        _check_section_id(s.section_id, "section_id"),
        _u8(s.active_nodes, "active_nodes"),
        _u16(s.packet_count, "packet_count"),
        _u16(s.delay_p50_s, "delay_p50_s"),
        _u16(s.delay_p90_s, "delay_p90_s"),
        0,  # reserved byte keeps the struct readable
        len(s.route_stubs),
    )
    for rid in s.route_stubs:
        body += struct.pack("<H", _u16(rid, "route_id"))
    return data_type_bytes(TYPE_SECT_SUM, body)


def decode_sect_sum(payload: bytes) -> SectSum:
    header, off = unpack_header(payload)
    if len(payload) < off + 10:
        raise CodecError("SECT_SUM too short")
    section_id, active, packets, p50, p90, _reserved, n = \
        struct.unpack_from("<BBHHHBB", payload, off)
    off += 10
    _check_section_id(section_id, "decoded section_id")
    if len(payload) < off + 2 * n:
        raise CodecError("SECT_SUM stubs truncated")
    stubs = [struct.unpack_from("<H", payload, off + 2 * i)[0]
             for i in range(n)]
    return SectSum(seq=header.seq, section_id=section_id,
                   active_nodes=active, packet_count=packets,
                   delay_p50_s=p50, delay_p90_s=p90, origin=header.origin,
                   route_stubs=stubs)


# --------------------------------------------------------------------------
# ROUTE (0x5303)
# --------------------------------------------------------------------------

@dataclass
class Route:
    seq: int
    section_id: int
    route_id: int
    packet_count: int
    delay_med_s: int
    last_heard_min: int
    origin: int = 0
    prefixes: List[int] = field(default_factory=list)  # 1 byte each


def encode_route(r: Route) -> bytes:
    if len(r.prefixes) > 255:
        raise CodecError("too many prefixes")
    body = pack_header(r.seq, r.origin)
    body += struct.pack(
        "<BHHHHB",
        _check_section_id(r.section_id, "section_id"),
        _u16(r.route_id, "route_id"),
        _u16(r.packet_count, "packet_count"),
        _u16(r.delay_med_s, "delay_med_s"),
        _u16(r.last_heard_min, "last_heard_min"),
        len(r.prefixes),
    )
    for pfx in r.prefixes:
        body += struct.pack("<B", _u8(pfx, "prefix"))
    return data_type_bytes(TYPE_ROUTE, body)


def decode_route(payload: bytes) -> Route:
    header, off = unpack_header(payload)
    if len(payload) < off + 10:
        raise CodecError("ROUTE too short")
    section_id, route_id, packets, delay, last, n = \
        struct.unpack_from("<BHHHHB", payload, off)
    _check_section_id(section_id, "decoded section_id")
    off += 10
    if len(payload) < off + n:
        raise CodecError("ROUTE prefixes truncated")
    prefixes = [payload[off + i] for i in range(n)]
    return Route(seq=header.seq, section_id=section_id, route_id=route_id,
                 packet_count=packets, delay_med_s=delay,
                 last_heard_min=last, origin=header.origin,
                 prefixes=prefixes)


# --------------------------------------------------------------------------
# INTRO (0x5304)
# --------------------------------------------------------------------------

@dataclass
class IntroEntry:
    prefix: int
    name: Optional[str] = None
    lat: Optional[float] = None
    lon: Optional[float] = None
    node_class: int = NODE_CLASS_UNKNOWN

    @property
    def flags(self) -> int:
        flags = 0
        if self.name:
            flags |= 0x01
        if self.lat is not None and self.lon is not None:
            flags |= 0x02
        flags |= (self.node_class & NODE_CLASS_MASK) << NODE_CLASS_SHIFT
        return flags


@dataclass
class Intro:
    seq: int = 0
    origin: int = 0
    entries: List[IntroEntry] = field(default_factory=list)
    # Deltas are relative to the LAYOUT centre/span (set by the builder);
    # the codec needs them to encode, and returns them on decode.
    center_lat: float = 0.0
    center_lon: float = 0.0
    span_m: float = 40000.0


def _position_deltas(intro: Intro, lat: float, lon: float) -> Tuple[int, int]:
    span_deg = intro.span_m / 111320.0
    dlat = round((lat - intro.center_lat) / span_deg * 32767)
    dlon = round((lon - intro.center_lon) / span_deg * 32767)
    dlat = max(-32767, min(32767, dlat))
    dlon = max(-32767, min(32767, dlon))
    return dlat, dlon


def _position_from_deltas(intro: Intro, dlat: int, dlon: int) -> Tuple[float, float]:
    span_deg = intro.span_m / 111320.0
    return (intro.center_lat + dlat / 32767.0 * span_deg,
            intro.center_lon + dlon / 32767.0 * span_deg)


def encode_intro(i: Intro) -> bytes:
    if len(i.entries) > 255:
        raise CodecError("too many intro entries")
    body = pack_header(i.seq, i.origin)
    body += struct.pack("<B", len(i.entries))
    for entry in i.entries:
        name_bytes = (entry.name or "").encode("utf-8")[:MAX_NAME]
        body += struct.pack("<BB", _u8(entry.prefix, "prefix"),
                            entry.flags)
        body += struct.pack("<B", len(name_bytes))
        if name_bytes:
            body += name_bytes
        if entry.flags & 0x02:
            dlat, dlon = _position_deltas(i, entry.lat, entry.lon)
            body += struct.pack("<hh", dlat, dlon)
    return data_type_bytes(TYPE_INTRO, body)


def decode_intro(payload: bytes, *, center_lat: float = 0.0,
                 center_lon: float = 0.0, span_m: float = 40000.0) -> Intro:
    """Decode INTRO. Positions are reconstructed from deltas against the
    LAYOUT the client already has (pass it here)."""
    header, off = unpack_header(payload)
    if len(payload) < off + 1:
        raise CodecError("INTRO too short")
    count = payload[off]
    off += 1
    intro = Intro(seq=header.seq, origin=header.origin,
                  center_lat=center_lat, center_lon=center_lon,
                  span_m=span_m)
    for _ in range(count):
        if len(payload) < off + 3:
            raise CodecError("INTRO entry truncated")
        prefix, flags = struct.unpack_from("<BB", payload, off)
        name_len = payload[off + 2]
        off += 3
        node_class = (flags >> NODE_CLASS_SHIFT) & NODE_CLASS_MASK
        name = None
        if flags & 0x01:
            if len(payload) < off + name_len:
                raise CodecError("INTRO name truncated")
            name = payload[off:off + name_len].decode("utf-8", "replace")
        off += name_len
        lat = lon = None
        if flags & 0x02:
            if len(payload) < off + 4:
                raise CodecError("INTRO position truncated")
            dlat, dlon = struct.unpack_from("<hh", payload, off)
            off += 4
            lat, lon = _position_from_deltas(
                Intro(center_lat=center_lat, center_lon=center_lon,
                      span_m=span_m), dlat, dlon)
        intro.entries.append(IntroEntry(prefix=prefix, name=name,
                                        lat=lat, lon=lon,
                                        node_class=node_class))
    return intro


# --------------------------------------------------------------------------
# LAYOUT (0x5305)
# --------------------------------------------------------------------------

@dataclass
class Layout:
    seq: int
    grid: int
    center_lat: float
    center_lon: float
    span_m: int
    origin: int = 0
    name: str = ""


def encode_layout(l: Layout) -> bytes:
    if not 2 <= l.grid <= 5:
        raise CodecError(f"grid out of range: {l.grid}")
    name_bytes = l.name.encode("utf-8")[:MAX_NAME]
    body = pack_header(l.seq, l.origin)
    body += struct.pack("<B", l.grid)
    body += struct.pack("<ii", round(l.center_lat * 1e6),
                        round(l.center_lon * 1e6))
    body += struct.pack("<H", _u16(l.span_m, "span_m"))
    body += struct.pack("<B", len(name_bytes))
    body += name_bytes
    return data_type_bytes(TYPE_LAYOUT, body)


def decode_layout(payload: bytes) -> Layout:
    header, off = unpack_header(payload)
    if len(payload) < off + 8:
        raise CodecError("LAYOUT too short")
    grid = payload[off]
    off += 1
    lat_e6, lon_e6 = struct.unpack_from("<ii", payload, off)
    off += 8
    span_m = struct.unpack_from("<H", payload, off)[0]
    off += 2
    if len(payload) < off + 1:
        raise CodecError("LAYOUT name length missing")
    name_len = payload[off]
    off += 1
    if len(payload) < off + name_len:
        raise CodecError("LAYOUT name truncated")
    name = payload[off:off + name_len].decode("utf-8", "replace")
    return Layout(seq=header.seq, grid=grid, center_lat=lat_e6 / 1e6,
                  center_lon=lon_e6 / 1e6, span_m=span_m,
                  origin=header.origin, name=name)


# --------------------------------------------------------------------------
# SNAP (0x5306)
# --------------------------------------------------------------------------

@dataclass
class Snap:
    seq: int
    snap_id: int
    part: int
    parts: int
    body: bytes
    origin: int = 0


def encode_snap(s: Snap) -> bytes:
    if len(s.body) > 255:
        raise CodecError(f"SNAP body too long: {len(s.body)}")
    body = pack_header(s.seq, s.origin)
    body += struct.pack("<BBB", _u8(s.snap_id, "snap_id"),
                        _u8(s.part, "part"), _u8(s.parts, "parts"))
    body += s.body
    return data_type_bytes(TYPE_SNAP, body)


def decode_snap(payload: bytes) -> Snap:
    header, off = unpack_header(payload)
    if len(payload) < off + 3:
        raise CodecError("SNAP too short")
    snap_id, part, parts = struct.unpack_from("<BBB", payload, off)
    off += 3
    return Snap(seq=header.seq, snap_id=snap_id, part=part, parts=parts,
                origin=header.origin, body=bytes(payload[off:]))


# --------------------------------------------------------------------------
# REFRESH_REQ (0x5311) - client -> host
# --------------------------------------------------------------------------

@dataclass
class RefreshReq:
    seq: int
    kind: int          # 1 = section, 2 = route
    target: int        # section_id or route_id
    nonce: int
    origin: int = 0    # client's own 2-byte id (v1.1)
    host: int = REFRESH_HOST_ANY  # preferred origin, 0 = owner decides
    # v1.3: the window the client wants, in km (20/40/60). 0 = host
    # decides = the whole 60x60 home box (today's behavior, and what
    # every pre-v1.3 encoder means when it omits the field).
    span_km: int = REFRESH_SPAN_HOST_DECIDES


def encode_refresh_req(r: RefreshReq) -> bytes:
    if r.kind not in (REFRESH_KIND_SECTION, REFRESH_KIND_ROUTE):
        raise CodecError(f"refresh kind invalid: {r.kind}")
    body = pack_header(r.seq, r.origin)
    body += struct.pack("<BHHH", r.kind, _u16(r.target, "target"),
                        _u16(r.host, "host"), _u16(r.nonce, "nonce"))
    # v1.3 (0x04): + span_km(2 LE). The version byte in the header is
    # what tells an old decoder "this body is longer than you think" -
    # and a strict old decoder REJECTS it loudly rather than misreads
    # (the same rule that guards unknown versions against us).
    body += struct.pack("<H", _u16(r.span_km, "span_km"))
    return data_type_bytes(TYPE_REFRESH_REQ, body)


def decode_refresh_req(payload: bytes) -> RefreshReq:
    header, off = unpack_header(payload)
    if header.version >= 0x04:
        # v1.3 body: kind(1) target(2) host(2) nonce(2) span_km(2)
        if len(payload) < off + 9:
            raise CodecError("REFRESH_REQ too short")
        kind, target, host = struct.unpack_from("<BHH", payload, off)
        nonce, span_km = struct.unpack_from("<HH", payload, off + 5)
    elif header.version >= 0x02:
        # v1.1 body: kind(1) target(2) host(2) nonce(2), no span_km
        if len(payload) < off + 7:
            raise CodecError("REFRESH_REQ too short")
        kind, target, host = struct.unpack_from("<BHH", payload, off)
        nonce = struct.unpack_from("<H", payload, off + 5)[0]
        span_km = REFRESH_SPAN_HOST_DECIDES
    else:
        # v1 body: kind(1) target(2) nonce(2), no host field
        if len(payload) < off + 5:
            raise CodecError("REFRESH_REQ too short")
        kind, target, nonce = struct.unpack_from("<BHH", payload, off)
        host = REFRESH_HOST_ANY
        span_km = REFRESH_SPAN_HOST_DECIDES
    return RefreshReq(seq=header.seq, kind=kind, target=target,
                      nonce=nonce, origin=header.origin, host=host,
                      span_km=span_km)


# --------------------------------------------------------------------------
# Generic decode + helpers
# --------------------------------------------------------------------------

def peek_data_type(payload: bytes) -> int:
    """The data_type of a full GRP_DATA plaintext (before decoding)."""
    if len(payload) < 3:
        raise CodecError("payload too short for data_type")
    return struct.unpack_from("<H", payload, 0)[0]


def decode_any(payload: bytes) -> object:
    """Decode any scope packet by its data_type."""
    data_type = peek_data_type(payload)
    return decode_body(data_type, payload[3:])


def decode_body(data_type: int, body: bytes) -> object:
    """Decode a scope BODY whose 3-byte type/len envelope is already
    stripped (what the companion delivers in CHANNEL_DATA_RECV: the
    radio decrypts and removes its own framing before queueing -
    meshcore reader.py sets payload = data_len bytes; openhop_core
    companion_base._handle_group_data_packet queues blob =
    plaintext[3:3+data_len])."""
    if data_type == TYPE_PULSE:
        return decode_pulse(body)
    if data_type == TYPE_SECT_SUM:
        return decode_sect_sum(body)
    if data_type == TYPE_ROUTE:
        return decode_route(body)
    if data_type == TYPE_INTRO:
        return decode_intro(body)
    if data_type == TYPE_LAYOUT:
        return decode_layout(body)
    if data_type == TYPE_SNAP:
        return decode_snap(body)
    if data_type == TYPE_REFRESH_REQ:
        return decode_refresh_req(body)
    raise CodecError(f"unknown data_type {data_type:#06x}")


# --------------------------------------------------------------------------
# Range guards
# --------------------------------------------------------------------------

def _u8(value: int, what: str) -> int:
    value = int(value)
    if not 0 <= value <= 0xFF:
        raise CodecError(f"{what} out of range: {value}")
    return value


def _u16(value: int, what: str) -> int:
    value = int(value)
    if not 0 <= value <= 0xFFFF:
        raise CodecError(f"{what} out of range: {value}")
    return value
